import React, { useState } from 'react';

const quoteData = [
    '"Framgång är att gå från misslyckande till misslyckande utan att förlora entusiasmen." - Winston Churchill',
    '"Var den förändring du vill se i världen." - Mahatma Gandhi',
    '"Det är aldrig för sent att vara det du kanske hade blivit." - George Eliot',
    '"Dröm stort och våga misslyckas." - Norman Vaughan',
    '"Det bästa sättet att förutsäga framtiden är att skapa den." - Peter Drucker',
    '"Målet i livet är inte att överleva, utan att trivas." - Maya Angelou',
    '"Lita på dig själv. Tänk för dig själv. Handla för dig själv. Tala för dig själv. Var dig själv. Älska dig själv." - Rollo May',
    '"För att uppnå storhet bör man inte bara handla, utan också drömma, inte bara planera, utan också tro." - Anatole France',
    '"Sätt ditt hjärta, sinne och själ i även dina minsta handlingar. Det är hemligheten till framgång." - Swami Sivananda',
    '"Ditt liv blir inte bättre genom att förändra omständigheterna, utan genom att förändra din inställning till dem." - Martha Beck',
    '"Det är inte vad som händer med dig, utan hur du reagerar på det som betyder något." - Epiktetos',
    '"Följ din passion, var beredd att arbeta hårt och förlora mycket sömn." - Dedikerad till Steve Jobs',
    '"Om du vill vara lycklig, var." - Leo Tolstoy',
    '"Varje dag kan inte vara bra, men det finns något bra i varje dag." - Alice Morse Earle',
    '"Uthållighet är inte att stå fast, utan att hålla fast vid det." - Josh Billings',
    '"Ingenting i världen kan ersätta uthållighet. Inte talang. Inte begåvning. Ingenting." - Calvin Coolidge',
    '"Var vänlig, för varje person du möter kämpar en kamp du inte vet något om." - Plato',
    '"Människor glömmer vad du sa, människor kommer att glömma vad du gjorde, men människor kommer aldrig att glömma hur du fick dem att känna." - Maya Angelou',
    '"Om du vill uppnå storhet, sluta fråga om du är kapabel till det och börja agera som om du är det." - Johann Wolfgang von Goethe',
    '"Må bra i ditt nuvarande ögonblick, och din rikedom kommer att manifestera sig." - Rhonda Byrne',
    '"Om du är förändringen du vill se, kommer du aldrig att känna dig övergiven." - Deepak Chopra',
    '"Varje ögonblick är en ny möjlighet att vara vad vi aldrig har varit." - P.D. James',
    '"Ditt liv är ditt budskap till världen. Se till att det är meningsfullt." - Unknown',
    '"Du är aldrig för gammal för att sätta ett nytt mål eller drömma en ny dröm." - C.S. Lewis',
    '"Framgång är att hoppa från misslyckande till misslyckande utan att förlora entusiasmen." - Abraham Lincoln',
    '"Om du inte kan göra något bra, så gör åtminstone inget ont." - Franklin D. Roosevelt',
    '"För att bli stor, börja där du är, använd vad du har, gör vad du kan." - Arthur Ashe',
    '"Att ge är att få." - Unknown',
    '"Älska livet du lever. Lever livet du älskar." - Bob Marley',
    '"För att vinna stora priser, är du tvungen att gå förbi det säkra." - Peter Drucker',
    '"Det är inte hur mycket vi gör, utan hur mycket kärlek vi lägger i det vi gör som räknas." - Mother Teresa',
    '"Lyckan är inte något klart gjort. Det kommer från dina egna handlingar." - Dalai Lama',
    '"Förmågan att hålla två tankar i huvudet samtidigt och ändå kunna fungera är en tecken på en intelligent människa." - F. Scott Fitzgerald',
    '"Vad vi tror om oss själva blir sanning för oss." - Louise Hay',
    '"I det ögonblick du ger upp är kampen över." - Louis L\'Amour',
    '"En människa som aldrig har gjort ett misstag har aldrig försökt något nytt." - Albert Einstein',
    '"Förändra ditt tankesätt och du förändrar din värld." - Norman Vincent Peale',
    '"För att uppleva en förändring måste du vara den förändring du vill se." - Mahatma Gandhi',
    '"Ju större svårighet, desto större ära att övervinna den." - Molière',
    '"Vägen till framgång och vägen till misslyckande är nästan exakt densamma." - Colin R. Davis',
    '"Våga, även om du är rädd." - H. Jackson Brown Jr.',
    '"Det är aldrig för sent att vara det du kanske hade blivit." - George Eliot',
    '"Du är din enda begränsning." - Jim Rohn',
    '"Framgång består av att gå från misslyckande till misslyckande utan att förlora entusiasmen." - Winston Churchill',
    '"Förändra ditt tankesätt och du förändrar din värld." - Norman Vincent Peale',
    '"Sätt ditt hjärta, sinne och själ i även dina minsta handlingar. Det är hemligheten till framgång." - Swami Sivananda',
    '"Ditt liv blir inte bättre genom att förändra omständigheterna, utan genom att förändra din inställning till dem." - Martha Beck',
    '"Följ din passion, var beredd att arbeta hårt och förlora mycket sömn." - Dedikerad till Steve Jobs',
    '"Om du vill vara lycklig, var." - Leo Tolstoy',
    '"Varje dag kan inte vara bra, men det finns något bra i varje dag." - Alice Morse Earle',
    '"Uthållighet är inte att stå fast, utan att hålla fast vid det." - Josh Billings',
    '"Ingenting i världen kan ersätta uthållighet. Inte talang. Inte begåvning. Ingenting." - Calvin Coolidge',
    '"Var vänlig, för varje person du möter kämpar en kamp du inte vet något om." - Plato',
    '"Människor glömmer vad du sa, människor kommer att glömma vad du gjorde, men människor kommer aldrig att glömma hur du fick dem att känna." - Maya Angelou',
    '"Om du vill uppnå storhet, sluta fråga om du är kapabel till det och börja agera som om du är det." - Johann Wolfgang von Goethe',
    '"Må bra i ditt nuvarande ögonblick, och din rikedom kommer att manifestera sig." - Rhonda Byrne',
    '"Om du är förändringen du vill se, kommer du aldrig att känna dig övergiven." - Deepak Chopra',
    '"Varje ögonblick är en ny möjlighet att vara vad vi aldrig har varit." - P.D. James',
    '"Ditt liv är ditt budskap till världen. Se till att det är meningsfullt." - Unknown',
    '"Du är aldrig för gammal för att sätta ett nytt mål eller drömma en ny dröm." - C.S. Lewis',
    '"Framgång är att hoppa från misslyckande till misslyckande utan att förlora entusiasmen." - Abraham Lincoln',
    '"Om du inte kan göra något bra, så gör åtminstone inget ont." - Franklin D. Roosevelt',
    '"För att bli stor, börja där du är, använd vad du har, gör vad du kan." - Arthur Ashe',
    '"Du måste vara den förändring du vill se i världen." - Mahatma Gandhi',
    '"Att ge är att få." - Unknown',
    '"Älska livet du lever. Lever livet du älskar." - Bob Marley',
    '"För att vinna stora priser, är du tvungen att gå förbi det säkra." - Peter Drucker',
    '"Det är inte hur mycket vi gör, utan hur mycket kärlek vi lägger i det vi gör som räknas." - Mother Teresa',
    '"Lyckan är inte något klart gjort. Det kommer från dina egna handlingar." - Dalai Lama',
    '"Förmågan att hålla två tankar i huvudet samtidigt och ändå kunna fungera är en tecken på en intelligent människa." - F. Scott Fitzgerald',
    '"Vad vi tror om oss själva blir sanning för oss." - Louise Hay',
    '"En människa som aldrig har gjort ett misstag har aldrig försökt något nytt." - Albert Einstein',
    '"Förändra ditt tankesätt och du förändrar din värld." - Norman Vincent Peale',
    '"För att uppleva en förändring måste du vara den förändring du vill se." - Mahatma Gandhi',
    '"Ju större svårighet, desto större ära att övervinna den." - Molière',
    '"Vägen till framgång och vägen till misslyckande är nästan exakt densamma." - Colin R. Davis',
    '"Våga, även om du är rädd." - H. Jackson Brown Jr.',
    '"Det är aldrig för sent att vara det du kanske hade blivit." - George Eliot',
    '"Du är din enda begränsning." - Jim Rohn',
    '"Framgång består av att gå från misslyckande till misslyckande utan att förlora entusiasmen." - Winston Churchill',
    '"Förändra ditt tankesätt och du förändrar din värld." - Norman Vincent Peale',
    '"Sätt ditt hjärta, sinne och själ i även dina minsta handlingar. Det är hemligheten till framgång." - Swami Sivananda',
    '"Ditt liv blir inte bättre genom att förändra omständigheterna, utan genom att förändra din inställning till dem." - Martha Beck',
    '"Följ din passion, var beredd att arbeta hårt och förlora mycket sömn." - Dedikerad till Steve Jobs',
    '"Om du vill vara lycklig, var." - Leo Tolstoy',
    '"Varje dag kan inte vara bra, men det finns något bra i varje dag." - Alice Morse Earle',
    '"Uthållighet är inte att stå fast, utan att hålla fast vid det." - Josh Billings',
    '"Ingenting i världen kan ersätta uthållighet. Inte talang. Inte begåvning. Ingenting." - Calvin Coolidge',
    '"Var vänlig, för varje person du möter kämpar en kamp du inte vet något om." - Plato',
    '"Om du vill uppnå storhet, sluta fråga om du är kapabel till det och börja agera som om du är det." - Johann Wolfgang von Goethe',
    '"Om du är förändringen du vill se, kommer du aldrig att känna dig övergiven." - Deepak Chopra',
    '"Varje ögonblick är en ny möjlighet att vara vad vi aldrig har varit." - P.D. James',                                   
  ];
  
  export default quoteData;